/*CREATE DATABASE hackathon; */

/*CREATE TABLE user (
	Id INT NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(200) NOT NULL,
    LastName VARCHAR(200) NOT NULL,
    Email VARCHAR(300),
    Username VARCHAR(200) NOT NULL, 
    Password VARCHAR(200) NOT NULL, 
    DateJoined DATETIME DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (Id) 
); */

